(ns grapplevents-rest.scraper.utils-test
  (:require [clojure.test :refer :all]
           [grapplevents-rest.scraper.utils :as utils]))

(deftest scraper-utils-not-empty
  (testing "not-empty?"
    (let [x nil
          y '()
          z [1 2 3]]
      (is (= false (utils/not-empty? x)))
      (is (= false (utils/not-empty? y)))
      (is (= true (utils/not-empty? z)))
      )))

(deftest resolve-month
  (testing "january"
    (is (= 1 (utils/resolve-month 1)))
    (is (= 1 (utils/resolve-month "jan")))
    (is (= 1 (utils/resolve-month "january")))
    (is (= 1 (utils/resolve-month "Janurary")))
    (is (= 1 (utils/resolve-month " janufary")))
    (is (= 1 (utils/resolve-month " ja")))
    (is (nil? (utils/resolve-month "j")))
    (is (nil? (utils/resolve-month "jn"))))
  (testing "february"
    (is (= 2 (utils/resolve-month 2)))
    (is (= 2 (utils/resolve-month "feb")))
    (is (= 2 (utils/resolve-month "february")))
    (is (= 2 (utils/resolve-month " Feburary")))
    (is (= 2 (utils/resolve-month " fE")))
    (is (= 2 (utils/resolve-month "ebruary")))
    (is (= 2 (utils/resolve-month "f"))))
  (testing "march"
    (is (= 3 (utils/resolve-month 3)))
    (is (= 3 (utils/resolve-month "mar")))
    (is (= 3 (utils/resolve-month "March")))
    (is (= 3 (utils/resolve-month " MaR ")))
    (is (nil? (utils/resolve-month "m")))
    (is (nil? (utils/resolve-month "mr"))))
  (testing "april"
    (is (= 4 (utils/resolve-month 4)))
    (is (= 4 (utils/resolve-month "apr")))
    (is (= 4 (utils/resolve-month "April")))
    (is (= 4 (utils/resolve-month " aP ")))
    (is (nil? (utils/resolve-month "a"))))
  (testing "may"
    (is (= 5 (utils/resolve-month 5)))
    (is (= 5 (utils/resolve-month "may")))
    (is (= 5 (utils/resolve-month "May")))
    (is (= 5 (utils/resolve-month " May ")))
    (is (nil? (utils/resolve-month "m")))
    (is (nil? (utils/resolve-month "my"))))
  (testing "june"
    (is (= 6 (utils/resolve-month 6)))
    (is (= 6 (utils/resolve-month "jun")))
    (is (= 6 (utils/resolve-month "june")))
    (is (= 6 (utils/resolve-month "June")))
    (is (= 6 (utils/resolve-month " june ")))
    (is (= 6 (utils/resolve-month "une")))
    (is (nil? (utils/resolve-month "j")))
    (is (nil? (utils/resolve-month "jn"))))
  (testing "july"
    (is (= 7 (utils/resolve-month 7)))
    (is (= 7 (utils/resolve-month "jul")))
    (is (= 7 (utils/resolve-month "july")))
    (is (= 7 (utils/resolve-month "July")))
    (is (= 7 (utils/resolve-month " july ")))
    (is (= 7 (utils/resolve-month "uly")))
    (is (nil? (utils/resolve-month "j")))
    (is (nil? (utils/resolve-month "jl"))))
  (testing "august"
    (is (= 8 (utils/resolve-month 8)))
    (is (= 8 (utils/resolve-month "aug")))
    (is (= 8 (utils/resolve-month "august")))
    (is (= 8 (utils/resolve-month "Auguzt")))
    (is (= 8 (utils/resolve-month " augrurt")))
    (is (nil? (utils/resolve-month "a")))
    (is (nil? (utils/resolve-month "ag"))))
  (testing "september"
    (is (= 9 (utils/resolve-month 9)))
    (is (= 9 (utils/resolve-month "sep")))
    (is (= 9 (utils/resolve-month "september")))
    (is (= 9 (utils/resolve-month "September")))
    (is (= 9 (utils/resolve-month " spetember")))
    (is (nil? (utils/resolve-month "s")))
    (is (nil? (utils/resolve-month "ember")))
    (is (nil? (utils/resolve-month "st"))))
  (testing "october"
    (is (= 10 (utils/resolve-month 10)))
    (is (= 10 (utils/resolve-month "oct")))
    (is (= 10 (utils/resolve-month "october")))
    (is (= 10 (utils/resolve-month "rocktober")))
    (is (= 10 (utils/resolve-month " october")))
    (is (nil? (utils/resolve-month "o")))
    (is (= 10 (utils/resolve-month "tober")))
    (is (= 10 (utils/resolve-month "oc"))))
  (testing "november"
    (is (= 11 (utils/resolve-month 11)))
    (is (= 11 (utils/resolve-month "nov")))
    (is (= 11 (utils/resolve-month "november")))
    (is (= 11 (utils/resolve-month "novem")))
    (is (= 11 (utils/resolve-month " vemb")))
    (is (nil? (utils/resolve-month "n")))
    (is (= 11 (utils/resolve-month "no"))))
  (testing "december"
    (is (= 12 (utils/resolve-month 12)))
    (is (= 12 (utils/resolve-month "dec")))
    (is (= 12 (utils/resolve-month "december")))
    (is (= 12 (utils/resolve-month "decem")))
    (is (= 12 (utils/resolve-month " cemb")))
    (is (= 12 (utils/resolve-month "d")))
    (is (nil? (utils/resolve-month "ecem"))))
  )
